import json
from datetime import datetime
from pathlib import Path

from crewai.tools import BaseTool
from pydantic import BaseModel, Field

from src.config import OUTPUTS_DIR
from src.exceptions import ReportGenerationError
from src.logger import log


class ReportGeneratorInput(BaseModel):
    dataset_info: str = Field(description="Dataset info JSON from schema inspector")
    cleaning_summary: str = Field(description="Summary of cleaning operations performed")
    feature_summary: str = Field(description="Summary of feature engineering")
    stats_summary: str = Field(description="Statistical analysis findings")
    model_results: str = Field(description="Model training results JSON")
    viz_charts: str = Field(description="List of generated chart paths")


class ReportGenerator(BaseTool):
    name: str = "report_generator"
    description: str = "Generate an executive summary report in Markdown format."
    args_schema: type[BaseModel] = ReportGeneratorInput

    def _run(self, dataset_info: str, cleaning_summary: str, feature_summary: str,
             stats_summary: str, model_results: str, viz_charts: str) -> str:
        OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)

        try:
            info = json.loads(dataset_info) if isinstance(dataset_info, str) else dataset_info
        except (json.JSONDecodeError, TypeError):
            info = {"raw": str(dataset_info)}

        try:
            models = json.loads(model_results) if isinstance(model_results, str) else model_results
        except (json.JSONDecodeError, TypeError):
            models = {"raw": str(model_results)}

        best_model = models.get("best_model") or {}
        results_list = models.get("results", [])

        report = f"""# AI Data Scientist Report

**Generated**: {datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")}

---

## 1. Dataset Overview

- **Rows**: {info.get('row_count', 'N/A')}
- **Columns**: {info.get('column_count', 'N/A')}
- **Missing Data**: {info.get('total_missing_pct', 'N/A')}%
- **Memory Usage**: {info.get('memory_usage_mb', 'N/A')} MB

## 2. Data Cleaning

{cleaning_summary}

## 3. Feature Engineering

{feature_summary}

## 4. Statistical Analysis

{stats_summary}

## 5. Model Performance

| Model | Accuracy | Precision | Recall | F1 | CV Score |
|-------|----------|-----------|--------|-----|----------|
"""
        for r in results_list:
            if "error" not in r:
                report += f"| {r.get('model_name', 'N/A')} | {r.get('accuracy', 'N/A')} | {r.get('precision', 'N/A')} | {r.get('recall', 'N/A')} | {r.get('f1', 'N/A')} | {r.get('cv_score_mean', 'N/A')} |\n"

        if best_model:
            report += f"""
**Best Model**: {best_model.get('model_name', 'N/A')}
**F1 Score**: {best_model.get('f1', 'N/A')}
**Accuracy**: {best_model.get('accuracy', 'N/A')}
"""

        try:
            charts = json.loads(viz_charts) if isinstance(viz_charts, str) else viz_charts
        except (json.JSONDecodeError, TypeError):
            charts = {"charts": []}

        chart_paths = charts.get("charts", []) if isinstance(charts, dict) else []
        if chart_paths:
            report += "\n## 6. Visualizations\n\n"
            for i, path in enumerate(chart_paths, 1):
                report += f"![Chart {i}]({path})\n\n"

        report += f"""
---

## 7. Recommendations

1. Deploy the best model ({best_model.get('model_name', 'N/A')}) for production use
2. Monitor model performance metrics over time
3. Consider collecting additional data for underrepresented features
4. Set up automated retraining pipeline

---

*Report generated by AI Data Scientist Platform*
"""

        report_path = OUTPUTS_DIR / "executive_report.md"
        with open(report_path, "w", encoding="utf-8") as f:
            f.write(report)

        log.info("report_generated", path=str(report_path))
        return f"Report generated successfully at {report_path}"
